#!/usr/bin/env bash
set -euo pipefail

echo "=== XerShop Deploy Guide ==="
echo ""
echo "No credit card needed! Pick one:"
echo ""
echo "1) Hugging Face Spaces (Docker) - 2vCPU, 16GB RAM"
echo "   Steps:"
echo "   - Go to https://huggingface.co -> Sign Up"
echo "   - Click profile -> New Space"
echo "   - Name: xershop, Space SDK: Docker"
echo "   - Dockerfile: Dockerfile.hf"
echo "   - Connect GitHub or upload files"
echo "   - Settings -> set env vars:"
echo "     JWT_SECRET = (random 32+ chars)"
echo "     TELEGRAM_BOT_TOKEN = your_bot_token"
echo "     TELEGRAM_CHAT_ID = your_chat_id"
echo "   - Your app at: https://username-xershop.hf.space"
echo ""
echo "2) Vercel (Frontend) + Hugging Face (Backend)"
echo "   Backend on HF Spaces (steps above)"
echo "   Frontend on Vercel:"
echo "   - Go to https://vercel.com -> Import GitHub"
echo "   - Pick printhub-web folder"
echo "   - Set NEXT_PUBLIC_API_URL = https://your-hf-space.hf.space/api/v1"
echo "   - Deploy"
echo ""
echo "3) Oracle Cloud (VM, full control)"
echo "   - Create free VM at https://cloud.oracle.com"
echo "   - SSH in and run:"
echo "     bash deploy.sh"
echo "   (needs credit card for signup, no charges)"
