package com.printhub;

import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class BCryptTest {
    @Test
    public void testPassword() {
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder(12);
        String hash = encoder.encode("admin123");
        System.out.println("NEW HASH FOR admin123: " + hash);
        assertTrue(encoder.matches("admin123", hash));
        // Test $2b$ hashes (generated by bcryptjs/node)
        assertTrue(encoder.matches("admin123", "$2b$12$sI.SaxwuQsNy5I5uTOdLEeQbpyY8ym0eIgO9sPaDXpS6OLOmn3T8W"));
        assertTrue(encoder.matches("shop123", "$2b$12$03BVYo27sULDFR.U9Ss3Wez9S66uak.PPRdk7yBwGejCSIKQVdsy6"));
    }
}
